Publero\AppleMobileBundle\Entity\AbstractStoreReceipt:
    type: mappedSuperclass
    fields:
        quantity:
            type: integer
        productId:
            name: product_id
            type: string
        transactionId:
            name: transaction_id
            type: string
        purchaseDate:
            name: purchase_date
            type: datetime
        originalTransactionId:
            name: original_transaction_id
            type: string
        originalPurchaseDate:
            name: original_purchase_date
            type: datetime
        itemId:
            name: item_id
            type: string
        applicationBundleId:
            name: application_bundle_id
            type: string
        applicationVersion:
            name: application_version
            type: string
        createDate:
            name: create_date
            type: datetime
            gedmo:
                timestampable:
                    on: create
