language: php

php:
    - 5.3
    - 5.4

env:
    - SYMFONY_VERSION=origin/master
    - SYMFONY_VERSION=dev-master

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev

notifications:
    email:
        - info@mhlavac.net